### PR TITLE
[chore] Refractor User class to remove duplicate methods.

### PR DESCRIPTION
**Pull request by arthurarty**
# What does this PR do?
These PR refractors the user class.

## Description of Task to be completed?
Refractor user class to remove duplicate functions that are handled in Database class.

### Acceptance criteria:
Maintainability badge should improve.
Status codes should be fixed.

What are the relevant pivotal tracker stories?
[160982828](https://www.pivotaltracker.com/story/show/160982828)

### CODE REVIEW

**Comment by billkabanga** [comment]
Good PR.
LGTM

**Comment by mozzy22** [comment]
ok that looks fine . cool

**Comment by walimike** [comment]
Thumbs up Blood

**Comment by walimike** [comment]
artur

**Comment by walimike** [comment]
review

**Pull request merged**
